version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.15.4
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ .Branch }}
            - v2-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - run:
          name: Run tests
          command: yarn test
