version: "2.1"

jobs:
  test:
    docker:
      - image: circleci/node:14.15.4
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ .Branch }}
            - v2-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - run:
          name: Run tests
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ .Branch }}
            - v2-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - run: 
          name: Login to GitHub
          command: |
            git config credential.helper 'cache --timeout=120'
            git config --global user.email "vineherbie@gmail.com"
            git config --global user.name "herbievine"
      - run:
          name: Clone staging branch
          working_directory: ~/app
          command: git clone -b staging --depth 1 "$CIRCLE_REPOSITORY_URL" clone
      - run:
          name: Deploy to main branch
          working_directory: ~/app/clone
          command: |
            git add .
            git push -q "$CIRCLE_REPOSITORY_URL" staging:main

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only: staging
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: staging
      